# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'macrosxBuild' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  # Pods for macrosxBuild

  target 'macrosxBuild-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'macrosxBuildTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'macrosxBuild-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for macrosxBuild-tvOS

end
